=== strixz-estg/PEI-WORK-25-26/xml_schemas/consultas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           elementFormDefault="qualified">
    
    <xs:element name="RegistoConsultas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Cabecalho"/>
                <xs:element ref="EspecialidadeRegisto" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="Cabecalho">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="HospitalID" type="xs:string"/>
                <xs:element name="RegistoID" type="xs:string"/> 
                <xs:element name="PeriodoReferencia">
                    <xs:complexType>
                        <xs:sequence>  <xs:element name="Mes">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Ano" type="xs:integer"/>
                        </xs:sequence> </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="EspecialidadeRegisto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Especialidade" type="xs:string"/>
                
                <xs:element name="PopulacaoAlvo">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="adulto"/>
                            <xs:enumeration value="crianca"/>
                            <xs:enumeration value="nao_aplicavel"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                
                <xs:element ref="ListasEspera"/>
                <xs:element ref="TemposMediosResposta"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="ListasEspera">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Geral" type="TipoUtentesLista"/>
                <xs:element name="NaoOncologica" type="TipoUtentesLista"/>
                <xs:element name="Oncologica" type="TipoUtentesLista"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="TipoUtentesLista">
        <xs:sequence>
            <xs:element name="UtentesEmLista">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="TemposMediosResposta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Normal" type="TipoTMR"/>
                <xs:element name="Prioritario" type="TipoTMR"/>
                <xs:element name="MuitoPrioritario" type="TipoTMR"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="TipoTMR">
        <xs:sequence>
            <xs:element name="TMR_dias">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== strixz-estg/PEI-WORK-25-26/xml_schemas/consultas.xml
<?xml version="1.0" encoding="UTF-8"?>
<RegistoConsultas 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="consultas.xsd">
    
    <Cabecalho>
        <HospitalID>HOSP_001</HospitalID>
        
        <RegistoID>CONS_HOSP_001_202510</RegistoID> 
        
        <PeriodoReferencia>
            <Mes>10</Mes>
            <Ano>2025</Ano>
        </PeriodoReferencia>
    </Cabecalho>
    
    <EspecialidadeRegisto>
        <Especialidade>Cardiologia</Especialidade>
        
        <PopulacaoAlvo>adulto</PopulacaoAlvo>
        
        <ListasEspera>
            <Geral>
                <UtentesEmLista>500</UtentesEmLista>
            </Geral>
            <NaoOncologica>
                <UtentesEmLista>450</UtentesEmLista>
            </NaoOncologica>
            <Oncologica>
                <UtentesEmLista>50</UtentesEmLista>
            </Oncologica>
        </ListasEspera>
        
        <TemposMediosResposta>
            <Normal>
                <TMR_dias>90</TMR_dias> </Normal>
            <Prioritario>
                <TMR_dias>45</TMR_dias> </Prioritario>
            <MuitoPrioritario>
                <TMR_dias>10</TMR_dias> </MuitoPrioritario>
        </TemposMediosResposta>
    </EspecialidadeRegisto>
    
</RegistoConsultas>
