=== strixz-estg/PEI-WORK-25-26/xml_schemas/Consultations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="InstitutionIdType">
        <xs:restriction base="xs:nonNegativeInteger"/>
    </xs:simpleType>
    <xs:simpleType name="HospitalNameType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="TargetPopulationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Adulto"/>
            <xs:enumeration value="CrianÃ§a"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="WaitingListCountsType">
        <xs:sequence>
            <xs:element name="General" type="xs:nonNegativeInteger"/>
            <xs:element name="NonOncological" type="xs:nonNegativeInteger"/>
            <xs:element name="Oncological" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="ConsultationsRegister">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="InstitutionId" type="InstitutionIdType"/>
                            <xs:element name="HospitalName" type="HospitalNameType"/>
                            <xs:element name="ReferencePeriod" type="xs:gYearMonth"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Consultation" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Speciality" type="xs:string"/>
                                        <xs:element name="TargetPopulation" type="TargetPopulationType"/>
                                        <xs:element name="WaitingListCounts" type="WaitingListCountsType"/>
                                        <xs:element name="AverageResponseTimes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Normal" type="xs:decimal"/>
                                                    <xs:element name="Priority" type="xs:decimal"/>
                                                    <xs:element name="VeryPriority" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== strixz-estg/PEI-WORK-25-26/xml_schemas/Consultations.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConsultationsRegister xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Consultations.xsd">
    <Header>
        <InstitutionId>151</InstitutionId>
        <HospitalName>Hospital São João</HospitalName>
        <ReferencePeriod>2025-11</ReferencePeriod>
    </Header>
    <Data>
        <Consultation>
            <Speciality>Cardiologia</Speciality>
            <TargetPopulation>Adulto</TargetPopulation>
            <WaitingListCounts>
                <General>100</General>
                <NonOncological>90</NonOncological>
                <Oncological>10</Oncological>
            </WaitingListCounts>
            <AverageResponseTimes>
                <Normal>30.5</Normal>
                <Priority>15.0</Priority>
                <VeryPriority>2.0</VeryPriority>
            </AverageResponseTimes>
        </Consultation>
    </Data>
</ConsultationsRegister>
