=== strixz-estg/PEI-WORK-25-26/xml_schemas/Services.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:simpleType name="TypeCodeType">
        <xs:restriction base="xs:int">
            <xs:enumeration value="1"/> <xs:enumeration value="2"/> </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="PriorityCodeType">
        <xs:restriction base="xs:int">
            <xs:enumeration value="0"/> <xs:enumeration value="1"/> <xs:enumeration value="2"/> <xs:enumeration value="3"/> </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="Services">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Service" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ServiceKey" type="xs:int" minOccurs="1"/>
                            <xs:element name="Speciality" type="xs:string" minOccurs="1"/>
                            <xs:element name="TypeCode" type="TypeCodeType" minOccurs="1"/>
                            <xs:element name="PriorityCode" type="PriorityCodeType" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== strixz-estg/PEI-WORK-25-26/xml_schemas/Services.xml
<?xml version="1.0" encoding="UTF-8"?>
<Services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Services.xsd">
    <Service>
        <ServiceKey>1</ServiceKey>
        <Speciality>Psiquiatria - Consulta Geral</Speciality>
        <TypeCode>2</TypeCode>
        <PriorityCode>1</PriorityCode>
    </Service>
    <Service>
        <ServiceKey>106</ServiceKey>
        <Speciality>Cirurgia Geral</Speciality>
        <TypeCode>1</TypeCode>
        <PriorityCode>3</PriorityCode>
    </Service>
</Services>
